Fix adblocker

diff --git a/zipping/onyx/META-INF/com/google/android/update-binary b/zipping/onyx/META-INF/com/google/android/update-binary
--- a/zipping/onyx/META-INF/com/google/android/update-binary
+++ b/zipping/onyx/META-INF/com/google/android/update-binary
@@ -12,7 +12,11 @@ ui_print() {
     shift;
   done;
 }
-show_progress() { echo "progress $1 $2" > $OUTFD; }
+
+show_progress() { 
+	echo "progress $1 $2" > $OUTFD; 
+}
+
 set_perm_recursive() {
   dirs=$(echo $* | $bb awk '{ print substr($0, index($0,$5)) }');
   for i in $dirs; do
@@ -21,44 +25,70 @@ set_perm_recursive() {
     find "$i" -type f -exec chmod $4 {} +;
   done;
 }
-file_getprop() { grep "^$2" "$1" | cut -d= -f2; }
-getprop() { test -e /sbin/getprop && /sbin/getprop $1 || file_getprop /default.prop $1; }
-abort() { ui_print "$*"; umount /system; umount /data; exit 1; }
+
+file_getprop() { 
+	grep "^$2" "$1" | cut -d= -f2; 
+}
+
+getprop() { 
+	test -e /sbin/getprop && /sbin/getprop $1 || file_getprop /default.prop $1; 
+}
+
+abort() { 
+	ui_print "$*"; 
+	umount /system; 
+	umount /data;
+	exit 1; 
+}
 
 show_progress 1.34 4;
 ui_print " ";
+
 mkdir -p /tmp/anykernel/bin;
 cd /tmp/anykernel;
 unzip -o "$ZIP";
+
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
+
 chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
 bb=/tmp/anykernel/tools/busybox;
 
-ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
+ui_print "### Heliox-Kernel ###";
 ui_print " ";
+ui_print "### Subhrajyoti Sen ###";
+ui_print " ";
+
+
 mount -o ro /system;
 mount /data;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
-  ui_print "Checking device...";
-  for i in 1 2 3 4 5; do
-    testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
-    if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
-      ui_print "$testname";
-      match=1;
-    fi;
-  done;
-  ui_print " ";
-  if [ "$match" != 1 ]; then
-    abort "Unsupported device. Aborting...";
-  fi;
+	ui_print "* Checking device compatibility...";
+	ui_print "  - Detected product.device: $(getprop ro.product.device)";
+	ui_print "  - Detected build.product : $(getprop ro.build.product)";
+
+	for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
+		testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
+		if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
+			match=1;
+		fi;
+	done;
+
+	if [ "$match" != 1 ]; then
+		abort "This kernel is NOT compatible with your device. Aborting.";
+	else
+		ui_print "  Kernel is compatible.";
+	fi;
+
+	ui_print " ";
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.initd)" == 1 ]; then
   ui_print "Creating init.d...";
   ui_print " ";
+
   mount -o remount,rw /system;
   mkdir /system/etc/init.d;
   set_perm_recursive 0 0 0755 0755 /system/etc/init.d;
@@ -66,13 +96,18 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.initd)" == 1 ]; then
 fi;
 
 ui_print "Installing kernel...";
+ui_print " ";
+
 for i in $($bb --list); do
   $bb ln -s $bb /tmp/anykernel/bin/$i;
 done;
+
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
   abort "Recovery busybox setup failed. Aborting...";
 fi;
+
 PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
+
 if [ $? != "0" ]; then
   abort;
 fi;
@@ -86,6 +121,7 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
   mount -o remount,ro /system;
 fi;
 
+mount -o remount,rw /system;
 ui_print "* Adding Ad-blocker..."
 rm -rf /system/etc/hosts
 cp -f /tmp/anykernel/system/hosts /system/etc/hosts;
